### ISSUE TITLE
初回起動時にOSU!フォルダを発見できないウィンドウが後ろに出る。

### ISSUE THREAD

**Issue by viasnake** [Siketyan/osu-Player#6]
ウィンドウは、「正しいOSU!フォルダを指定してください。」という警告だと思うのですが、そのウィンドウが初回起動時にロゴの後ろに出ます。

OSU!を通常のルートと違う場所へインストールしている為、初回の読み込みで出てきているのかと思います。
![img](https://user-images.githubusercontent.com/6961187/34412588-7f473c38-ec21-11e7-851e-8b3f2705202c.PNG)

**Comment by siketyan** [comment]
ご報告ありがとうございます。確認します。
確認の結果及び修正の進捗はこちらに返信します。

**Comment by siketyan** [comment]
確認した結果、ご報告の通りロゴ（スプラッシュスクリーン）にosu!フォルダ指定を促すメッセージウィンドウが隠れる現象が発生しました。
また、スプラッシュスクリーンは常に最前面に表示するよう設定しているため、正常に操作できませんでした。
今すぐ緊急修正を行い、コミット及びリリースを行います。（developブランチではなくhotfixブランチで扱います）

**Comment by siketyan** [comment]
バージョン 1.3.2 にてこの問題を修正しました。
https://github.com/Siketyan/osu-Player/releases/tag/v1.3.2
ご迷惑をおかけし申し訳ありませんでした。
